### PR TITLE
Moved provider to top of hierarchy

### PR DESCRIPTION
**Pull request by jpreecedev**

### CODE REVIEW

**Comment by warisanwar** [comment]
Thank you,It's working smoothly now

**Comment by jpreecedev** [comment]
Glad I could help

**Comment by warisanwar** [comment]
Hey,I am facing one issue,whenever i'm restarting the page,the filter i applied and the state resets .It happens in my project and yours as well.
Please look into it :D

**Comment by jpreecedev** [comment]
Are you saying that the state is lost when you refresh the page?

**Comment by warisanwar** [comment]
Yes,The filters that we apply resets and it shows the state without the filters applied.(on page refresh)

**Comment by jpreecedev** [comment]
yes that makes perfect sense and is expected behaviour.  I would suggest using something like local storage to save the stage on change, and load it on initial load.  

Your redux store initialisation code would look something like this (I guess);

```
import { createStore, combineReducers, applyMiddleware } from "redux"
import thunk from "redux-thunk"
import { reducer as formReducer } from "redux-form"
import { composeWithDevTools } from "redux-devtools-extension"

import * as actions from "./actions"
import { picturesReducer } from "./reducers"
import { AppState } from "../global"

const rootReducer = combineReducers({
  pictures: picturesReducer,
  form: formReducer
})

const loadState = () => {
  try {
    const serializedState = localStorage.getItem("state")
    if (serializedState === null) {
      return {}
    }
    return JSON.parse(serializedState)
  } catch (err) {
    return {}
  }
}
const saveState = (state: AppState) => {
  try {
    const serializedState = JSON.stringify(state)
    localStorage.setItem("state", serializedState)
  } catch {
    // ignore write errors
  }
}

const initialiseStore = (initialState: AppState = loadState()) => {
  const store = createStore(rootReducer, initialState, composeWithDevTools(applyMiddleware(thunk)))

  store.subscribe(() => {
    saveState(<AppState>{
      pictures: store.getState().pictures
    })
  })

  return store
}

export { initialiseStore, actions, rootReducer }

```

Ofc you need to edit this for your project, i just copied this from some random repo I have

**Comment by warisanwar** [comment]
Oh cool, can't we do something without redux?
As i've done the whole project with context api only,and i don't have much knowledge of redux yet.

**Comment by jpreecedev** [comment]
Ah sorry had a little moment there, I've got redux on the brain atm.

As this is a class based component, its pretty simple.  One approach is to update the `updateFilter` function.  The `setState` call takes a second argument, which is invoked after the state has been updated.

```
const loadState = () => {
  try {
    const serializedState = localStorage.getItem("state")
    if (serializedState === null) {
      return {}
    }
    return JSON.parse(serializedState)
  } catch (err) {
    return {}
  }
}
const saveState = (state: AppState) => {
  try {
    const serializedState = JSON.stringify(state)
    localStorage.setItem("state", serializedState)
  } catch {
    // ignore write errors
  }
}
```

You could call the `saveState` function on there.

You could add the `loadState` called in either the constructor, or the `componentDidMount` lifecycle function.  Ofc update the `loadState` function to call `setState` with the deserialised state from local storage. 

This is ofc just one approach but it should work fine and dandy.

**Comment by warisanwar** [comment]
I'm stuck with the code 

Please correct me or just make a pull request and add the code as im not able to figure it out :(

```
import * as React from 'react'

const DefaultState = {
  propertyListings: [],
  filter: {}
}

const PropertyListingsContext = React.createContext(DefaultState)

export const PropertyListingsConsumer = PropertyListingsContext.Consumer


export class PropertyListingsProvider extends React.Component {
  constructor(props){
    super(props);
    loadState();

  }
  static applyFilter(listings, filter) {
    const { priceFrom, postcode, sortOrder } = filter
    let result = listings
    if (priceFrom) {
      const from = priceFrom
      result = result.filter(item => item.price >= from)
    }
    if (postcode) {
      result = result.filter(item => item.postcode.toLowerCase().startsWith(postcode))
    }
    if (sortOrder) {
      if (sortOrder === 'highestfirst') {
        result = result.sort((a, b) => b.price - a.price)
      }
      if (sortOrder === 'lowestfirst') {
        result = result.sort((a, b) => a.price - b.price)
      }
    }
    return result
  }

  state = DefaultState

   loadState = () => {
    try {
      const serializedState = localStorage.getItem("state")
      if (serializedState === null) {
        return {}
      }
      return JSON.parse(serializedState)
    } catch (err) {
      return {}
    }
  }
   saveState = (state) => {
    try {
      const serializedState = JSON.stringify(state)
      localStorage.setItem("state", serializedState)
    } catch {
      // ignore write errors
    }
  }

  componentDidMount() {
    fetch('/server/listings.json')
      .then(res => res.json())
      .then(res => {
        this.setState({ propertyListings: res })
      })
  }

  getListingByPropertyId = propertyId => {
    const { propertyListings } = this.state
    return propertyListings.find(listing => listing.id === Number(propertyId))
  }

  

  updateFilter = filter => {
    this.setState({
      filter
    },saveState(filter))
  }

  render() {
    const { children } = this.props
    const { propertyListings, filter } = this.state

    
    const filteredListings = PropertyListingsProvider.applyFilter(
      propertyListings,
      filter
    )
    console.log(propertyListings)
    return (
      <PropertyListingsContext.Provider
        value={{
          allListings: propertyListings,
          propertyListings: filteredListings,
          updateFilter: this.updateFilter,
          getListingByPropertyId: this.getListingByPropertyId
        }}
      >
        {children}
      </PropertyListingsContext.Provider>
    )
  }
}
```

**Comment by jpreecedev** [comment]
I'd rather help you fix it, as you will learn better.

I haven't tried your code, but first thoughts are this;

```
  updateFilter = filter => {
    this.setState({
      filter
    },() => saveState(filter))
  }
```

Your `loadState` call in the constructor does nothing.  I'd suggest moving it to `componentDidMount` and then use the result of the call to `setState`

**Comment by warisanwar** [comment]
It worked , i tried tinkering around and now it's perfect.
Thanks for  helping me fix it :D
Your project has helped my website a lot 👍

**Comment by jpreecedev** [comment]
Happy to help

**Comment by warisanwar** [comment]
Hey,need small help on this one, i'm trying to navigate to the listings component,but i'm not able to navigate,
the onClick prop updates the state in the context api through the consumer.

```
<PropertyListingsConsumer>
		{({handleClick})=>(
			<>
		    <li className="nav-item">
			<Link 
			    className="nav-link" 
			    style={{cursor:'pointer'}} 
		            value='rent' 
			    onClick={handleClick}
			   to="/listings"
			 >Rent</Link>
                     </li>
			</>
			)}
</PropertyListingsConsumer>
```

**Comment by jpreecedev** [comment]
I suggest you move this conversation to stackoverflow. Thanks.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Pull request merged**
